-- 1. Create cart_items table
create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete cascade not null,
  quantity integer not null default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, product_id)
);

-- 2. Enable RLS
alter table public.cart_items enable row level security;

-- 3. Policies
create policy "Users can view their own cart items"
  on public.cart_items for select
  using (auth.uid() = user_id);

create policy "Users can insert their own cart items"
  on public.cart_items for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own cart items"
  on public.cart_items for update
  using (auth.uid() = user_id);

create policy "Users can delete their own cart items"
  on public.cart_items for delete
  using (auth.uid() = user_id);

-- 4. Populate Products (Idempotent insert)
-- We insert products with specific IDs to match the frontend constants
insert into public.products (id, name, description, price_cents, image_url, category_id, is_active)
values 
  (1, 'Côte de Bœuf VBF', 'Une pièce d’exception, persillée et tendre. Idéale pour les grillades.', 2990, '/images/cote-de-boeuf.png', null, true),
  (2, 'Poulet Fermier Label Rouge', 'Élevé en plein air, chair ferme et goût authentique.', 1250, '/images/poulet-fermier.png', null, true),
  (3, 'Foie de Veau', 'Coupe artisanale fine, riche en fer et en saveur.', 1890, '/images/foie-de-veau.png', null, true),
  (4, 'Gigot d''Agneau', 'Tendre et savoureux, parfait pour vos rôtis du dimanche.', 2490, '/images/gigot-agneau.png', null, true),
  (5, 'Saucisses Maison', 'Préparées sur place avec des épices sélectionnées.', 1490, '/images/Saucisses Maison.png', null, true),
  (6, 'Cœur de Bœuf', 'Une pièce technique préparée par votre artisan.', 990, '/images/coeur-de-boeuf.png', null, true)
on conflict (id) do update 
set 
  name = excluded.name,
  description = excluded.description,
  price_cents = excluded.price_cents,
  image_url = excluded.image_url;
