-- Enable Row Level Security
alter table public.profiles enable row level security;
alter table public.products enable row level security;
-- Create categories table if it doesn't exist
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add category_id to products if it doesn't exist (it seems it does based on AdminProducts.tsx)
-- But let's ensure the foreign key constraint
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'products' and column_name = 'category_id') then
    alter table public.products add column category_id bigint references public.categories(id);
  end if;
end $$;

-- Update profiles table to include email if it's not there
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'email') then
    alter table public.profiles add column email text;
  end if;
end $$;

-- Update profiles table to include phone if it's not there
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'phone') then
    alter table public.profiles add column phone text;
  end if;
end $$;

-- Create Storage Bucket for Products
insert into storage.buckets (id, name, public)
values ('products', 'products', true)
on conflict (id) do nothing;

-- Storage Policies
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'products' );

create policy "Admin Upload Access"
  on storage.objects for insert
  with check ( bucket_id = 'products' AND auth.role() = 'authenticated' ); -- Refine this later for admin only if possible

create policy "Admin Update Access"
  on storage.objects for update
  using ( bucket_id = 'products' AND auth.role() = 'authenticated' );

create policy "Admin Delete Access"
  on storage.objects for delete
  using ( bucket_id = 'products' AND auth.role() = 'authenticated' );

-- Trigger to handle new user signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email, phone, role)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.email,
    new.raw_user_meta_data->>'phone',
    coalesce(new.raw_user_meta_data->>'role', 'user')
  );
  return new;
end;
$$;

-- Drop trigger if exists to recreate it
drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Policies for Categories
alter table public.categories enable row level security;

create policy "Public categories are viewable by everyone"
  on public.categories for select
  using ( true );

create policy "Admins can insert categories"
  on public.categories for insert
  with check ( auth.uid() in (select id from public.profiles where role = 'admin') );

create policy "Admins can update categories"
  on public.categories for update
  using ( auth.uid() in (select id from public.profiles where role = 'admin') );

create policy "Admins can delete categories"
  on public.categories for delete
  using ( auth.uid() in (select id from public.profiles where role = 'admin') );
