-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES (Users)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  phone text,
  role text default 'user',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

create policy "Users can insert their own profile." on public.profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on public.profiles
  for update using (auth.uid() = id);

-- Trigger to handle new user signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, phone, role)
  values (
    new.id, 
    new.email, 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'phone',
    'user' -- Default role
  );
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 2. CATEGORIES
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.categories enable row level security;

create policy "Categories are viewable by everyone." on public.categories
  for select using (true);

create policy "Admins can insert categories" on public.categories
  for insert with check (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

create policy "Admins can update categories" on public.categories
  for update using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

create policy "Admins can delete categories" on public.categories
  for delete using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- 3. PRODUCTS
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price_cents integer not null, -- Price in cents
  image_url text,
  category_id bigint references public.categories(id) on delete set null,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.products enable row level security;

create policy "Products are viewable by everyone." on public.products
  for select using (true);

create policy "Admins can insert products" on public.products
  for insert with check (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

create policy "Admins can update products" on public.products
  for update using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

create policy "Admins can delete products" on public.products
  for delete using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- 4. ORDERS
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null, -- Nullable for guest checkout if needed
  status text default 'pending', -- pending, processing, shipped, delivered, cancelled
  payment_status text default 'pending', -- pending, paid, refunded
  total_cents integer not null,
  customer_name text not null, -- Snapshot of customer name
  delivery_address text not null,
  contact_email text not null,
  contact_phone text not null,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.orders enable row level security;

create policy "Users can view their own orders." on public.orders
  for select using (auth.uid() = user_id);

create policy "Admins can view all orders." on public.orders
  for select using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

create policy "Users can insert their own orders." on public.orders
  for insert with check (auth.uid() = user_id);

create policy "Admins can update orders" on public.orders
  for update using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- 5. ORDER ITEMS
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete set null,
  quantity integer not null,
  price_cents integer not null, -- Snapshot of price
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.order_items enable row level security;

create policy "Users can view their own order items." on public.order_items
  for select using (exists (select 1 from orders where orders.id = order_items.order_id and orders.user_id = auth.uid()));

create policy "Admins can view all order items." on public.order_items
  for select using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

create policy "Users can insert their own order items." on public.order_items
  for insert with check (exists (select 1 from orders where orders.id = order_items.order_id and orders.user_id = auth.uid()));

-- 6. CONTACT MESSAGES
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  subject text,
  message text not null,
  read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.contact_messages enable row level security;

create policy "Admins can view all contact messages." on public.contact_messages
  for select using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

create policy "Anyone can insert contact messages." on public.contact_messages
  for insert with check (true);

-- 7. STORAGE (Products Bucket)
-- Note: Creating buckets via SQL is supported in Supabase
insert into storage.buckets (id, name, public) 
values ('products', 'products', true)
on conflict (id) do nothing;

-- Storage Policies
create policy "Public Access" on storage.objects 
  for select using ( bucket_id = 'products' );

create policy "Admin Upload" on storage.objects 
  for insert with check ( 
    bucket_id = 'products' 
    and exists (select 1 from profiles where id = auth.uid() and role = 'admin') 
  );

create policy "Admin Update" on storage.objects 
  for update using ( 
    bucket_id = 'products' 
    and exists (select 1 from profiles where id = auth.uid() and role = 'admin') 
  );

create policy "Admin Delete" on storage.objects 
  for delete using ( 
    bucket_id = 'products' 
    and exists (select 1 from profiles where id = auth.uid() and role = 'admin') 
  );
